_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 40
  # 4-channel input
  PIXEL_MEAN: [103.530, 116.280, 123.675, 0.0]
  PIXEL_STD: [1.0, 1.0, 1.0, 1.0]

DATASETS:
    TRAIN: ("youtube_vis_train",)
    TEST: ("youtube_vis_train",)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 100000

OUTPUT_DIR:
  ./exp/
